export const emailEvents = {
  waitlistSignup: "waitlist.signup",
  contactCreated: "contact.created",
  accountCreated: "account.created",
  passwordResetRequested: "account.password_reset_requested",
  orderCreated: "order.created",
  paymentPending: "payment.pending",
  paymentNotFinished: "payment.not_finished",
  paymentApproved: "payment.approved",
  paymentFailed: "payment.failed",
  internalNewSaleAlert: "internal.new_sale_alert",
  internalLowStockAlert: "internal.low_stock_alert",
  internalPaymentFailedAlert: "internal.payment_failed_alert",
  orderPreparing: "order.preparing",
  orderShipped: "order.shipped",
  orderDelivered: "order.delivered",
  reviewRequested: "review.requested",
  abandonedCartReminder1: "marketing.abandoned_cart.reminder_1",
  abandonedCartReminder2: "marketing.abandoned_cart.reminder_2",
  abandonedCartReminder3: "marketing.abandoned_cart.reminder_3",
  launchAnnouncement: "marketing.launch_announcement",
  newDropAnnouncement: "marketing.new_drop_announcement",
  newProductsAnnouncement: "marketing.new_products_announcement",
  promotionEmail: "marketing.promotion",
  crossSellEmail: "marketing.cross_sell",
  loyaltyCouponEmail: "marketing.loyalty_coupon",
};
