export const emailSubjects = {
  comingSoonConfirmation: "Sua entrada antecipada na L4CKOS foi confirmada",
  contactConfirmation: "Recebemos sua mensagem. A L4CKOS vai responder em breve",
  newContactInternal: ({ subject }) => `Novo contato do site: ${subject || "L4CKOS"}`,
  welcomeAccount: "Sua conta L4CKOS está pronta para uso",
  passwordReset: "Redefina seu acesso com segurança",
  paymentNotFinished: ({ orderNumber }) => `Seu pedido #${orderNumber} ainda pode ser concluído`,
  orderCreated: ({ orderNumber }) => `Pedido #${orderNumber} criado com sucesso`,
  paymentPending: ({ orderNumber }) => `Finalize o pagamento do pedido #${orderNumber}`,
  paymentApproved: ({ orderNumber }) => `Pagamento confirmado para o pedido #${orderNumber}`,
  paymentFailed: ({ orderNumber }) => `O pagamento do pedido #${orderNumber} não foi concluído`,
  internalNewSaleAlert: ({ orderNumber }) => `Nova venda confirmada: pedido #${orderNumber}`,
  internalLowStockAlert: ({ totalProducts }) => `Alerta operacional: ${totalProducts || 0} item(ns) com estoque baixo`,
  internalPaymentFailedAlert: ({ orderNumber }) => `Falha de pagamento no pedido #${orderNumber}`,
  orderPreparing: ({ orderNumber }) => `Seu pedido #${orderNumber} entrou em separação`,
  orderShipped: ({ orderNumber }) => `Seu pedido #${orderNumber} já está em rota`,
  orderDelivered: ({ orderNumber }) => `Pedido #${orderNumber} entregue`,
  reviewRequest: ({ orderNumber }) => `Como foi receber o pedido #${orderNumber}?`,
  launchAnnouncement: "A L4CKOS abriu. Entre antes do primeiro giro acabar",
  newDropAnnouncement: "Novo drop liberado na L4CKOS",
  newProductsAnnouncement: "Novidades recém-chegadas na L4CKOS",
  promotionEmail: "Condição especial ativa por tempo limitado",
  abandonedCartReminder1: "Seu carrinho L4CKOS continua pronto para fechar",
  abandonedCartReminder2: "Ainda dá tempo de concluir a sua seleção",
  abandonedCartReminder3: "Último aviso: sua seleção pode sair do estoque",
  crossSellEmail: "Itens que completam sua última compra",
  loyaltyCouponEmail: "Seu benefício de fidelidade já está ativo",
};
