export const emailSubjects = {
  comingSoonConfirmation: "Sua entrada antecipada na L4CKOS foi confirmada",
  contactConfirmation: "Recebemos sua mensagem. A L4CKOS vai responder em breve",
  newContactInternal: ({ subject }) => `Novo contato do site: ${subject || "L4CKOS"}`,
  welcomeAccount: "Sua conta L4CKOS esta pronta para uso",
  passwordReset: "Redefina seu acesso com seguranca",
  paymentNotFinished: ({ orderNumber }) => `Seu pedido #${orderNumber} ainda pode ser concluido`,
  orderCreated: ({ orderNumber }) => `Pedido #${orderNumber} criado com sucesso`,
  paymentPending: ({ orderNumber }) => `Finalize o pagamento do pedido #${orderNumber}`,
  paymentApproved: ({ orderNumber }) => `Pagamento confirmado para o pedido #${orderNumber}`,
  paymentFailed: ({ orderNumber }) => `O pagamento do pedido #${orderNumber} nao foi concluido`,
  internalNewSaleAlert: ({ orderNumber }) => `Nova venda confirmada: pedido #${orderNumber}`,
  internalLowStockAlert: ({ totalProducts }) => `Alerta operacional: ${totalProducts || 0} item(ns) com estoque baixo`,
  internalPaymentFailedAlert: ({ orderNumber }) => `Falha de pagamento no pedido #${orderNumber}`,
  orderPreparing: ({ orderNumber }) => `Seu pedido #${orderNumber} entrou em separacao`,
  orderShipped: ({ orderNumber }) => `Seu pedido #${orderNumber} ja esta em rota`,
  orderDelivered: ({ orderNumber }) => `Pedido #${orderNumber} entregue`,
  reviewRequest: ({ orderNumber }) => `Como foi receber o pedido #${orderNumber}?`,
  launchAnnouncement: "A L4CKOS abriu. Entre antes do primeiro giro acabar",
  newDropAnnouncement: "Novo drop liberado na L4CKOS",
  newProductsAnnouncement: "Novidades recem-chegadas na L4CKOS",
  promotionEmail: "Condicao especial ativa por tempo limitado",
  abandonedCartReminder1: "Seu carrinho L4CKOS continua pronto para fechar",
  abandonedCartReminder2: "Ainda da tempo de concluir a sua selecao",
  abandonedCartReminder3: "Ultimo aviso: sua selecao pode sair do estoque",
  crossSellEmail: "Itens que completam sua ultima compra",
  loyaltyCouponEmail: "Seu beneficio de fidelidade ja esta ativo",
};
