export const emailSubjects = {
  comingSoonConfirmation: "Voce entrou na lista de espera da L4CKOS",
  contactConfirmation: "Recebemos sua mensagem - L4CKOS",
  newContactInternal: ({ subject }) => `Novo contato do site - ${subject || "L4CKOS"}`,
  welcomeAccount: "Sua conta L4CKOS foi criada",
  passwordReset: "Redefina sua senha - L4CKOS",
  orderCreated: ({ orderNumber }) => `Pedido #${orderNumber} recebido`,
  paymentPending: ({ orderNumber }) => `Pagamento pendente - Pedido #${orderNumber}`,
  paymentApproved: ({ orderNumber }) => `Pagamento aprovado - Pedido #${orderNumber}`,
  paymentFailed: ({ orderNumber }) => `Pagamento nao aprovado - Pedido #${orderNumber}`,
  orderPreparing: ({ orderNumber }) => `Seu pedido entrou em preparacao - #${orderNumber}`,
  orderShipped: ({ orderNumber }) => `Seu pedido foi enviado - #${orderNumber}`,
  orderDelivered: ({ orderNumber }) => `Pedido entregue - #${orderNumber}`,
  reviewRequest: ({ orderNumber }) => `Como foi seu pedido #${orderNumber}?`,
  launchAnnouncement: "L4CKOS esta no ar",
  newDropAnnouncement: "Novo drop L4CKOS",
  promotionEmail: "Selecao especial L4CKOS",
  abandonedCartReminder1: "Seu carrinho L4CKOS ainda esta te esperando",
  abandonedCartReminder2: "Os itens do seu carrinho continuam disponiveis",
  abandonedCartReminder3: "Ultimo aviso sobre o seu carrinho",
  crossSellEmail: "Complete seu setup L4CKOS",
  loyaltyCouponEmail: "Seu proximo passo na L4CKOS",
};
